// <auto-generated />
using System;
using DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20251023081025_MigratonName1")]
    partial class MigratonName1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Группы", b =>
                {
                    b.Property<int>("IdГруппы")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_группы");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdГруппы"));

                    b.Property<int>("IdСпециальности")
                        .HasColumnType("int")
                        .HasColumnName("ID_специальности");

                    b.Property<int>("ГодПоступления")
                        .HasColumnType("int")
                        .HasColumnName("Год_поступления");

                    b.Property<int>("Курс")
                        .HasColumnType("int");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdГруппы")
                        .HasName("PK__Группы__7EC7037D9B754A1C");

                    b.HasIndex("IdСпециальности");

                    b.HasIndex(new[] { "Название" }, "UQ__Группы__38DA8035B4795D03")
                        .IsUnique();

                    b.ToTable("Группы", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Задания", b =>
                {
                    b.Property<int>("IdЗадания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_задания");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdЗадания"));

                    b.Property<int>("IdОсвобождения")
                        .HasColumnType("int")
                        .HasColumnName("ID_освобождения");

                    b.Property<int>("IdТипаЗадания")
                        .HasColumnType("int")
                        .HasColumnName("ID_типа_задания");

                    b.Property<DateOnly>("ДатаНазначения")
                        .HasColumnType("date")
                        .HasColumnName("Дата_назначения");

                    b.Property<string>("Описание")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("СрокСдачи")
                        .HasColumnType("date")
                        .HasColumnName("Срок_сдачи");

                    b.Property<string>("Тема")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdЗадания")
                        .HasName("PK__Задания__D3DD242A3E9D8E9C");

                    b.HasIndex("IdОсвобождения");

                    b.HasIndex("IdТипаЗадания");

                    b.ToTable("Задания", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Нагрузка", b =>
                {
                    b.Property<int>("IdНагрузки")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_нагрузки");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdНагрузки"));

                    b.Property<int>("IdГруппы")
                        .HasColumnType("int")
                        .HasColumnName("ID_группы");

                    b.Property<int>("IdПреподавателя")
                        .HasColumnType("int")
                        .HasColumnName("ID_преподавателя");

                    b.Property<int>("Семестр")
                        .HasColumnType("int");

                    b.Property<int>("УчебныйГод")
                        .HasColumnType("int")
                        .HasColumnName("Учебный_год");

                    b.HasKey("IdНагрузки")
                        .HasName("PK__Нагрузка__5784711A82DFB935");

                    b.HasIndex("IdГруппы");

                    b.HasIndex(new[] { "IdПреподавателя", "IdГруппы", "Семестр", "УчебныйГод" }, "UQ__Нагрузка__036905DA55B07A86")
                        .IsUnique();

                    b.ToTable("Нагрузка", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Освобождения", b =>
                {
                    b.Property<int>("IdОсвобождения")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_освобождения");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdОсвобождения"));

                    b.Property<int>("IdПричины")
                        .HasColumnType("int")
                        .HasColumnName("ID_причины");

                    b.Property<int>("IdСтудента")
                        .HasColumnType("int")
                        .HasColumnName("ID_студента");

                    b.Property<DateOnly>("ДатаНачала")
                        .HasColumnType("date")
                        .HasColumnName("Дата_начала");

                    b.Property<DateOnly>("ДатаОкончания")
                        .HasColumnType("date")
                        .HasColumnName("Дата_окончания");

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("КемВыдано")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Кем_выдано");

                    b.Property<string>("НомерСправки")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Номер_справки");

                    b.Property<string>("Примечание")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdОсвобождения")
                        .HasName("PK__Освобожд__6A05CE556E5CD89C");

                    b.HasIndex("IdПричины");

                    b.HasIndex("IdСтудента");

                    b.ToTable("Освобождения", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Отделения", b =>
                {
                    b.Property<int>("IdОтделения")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_отделения");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdОтделения"));

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Заведующий")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdОтделения")
                        .HasName("PK__Отделени__A935EBC47FF3FA16");

                    b.HasIndex(new[] { "Название" }, "UQ__Отделени__38DA8035BF01208B")
                        .IsUnique();

                    b.ToTable("Отделения", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Оценки", b =>
                {
                    b.Property<int>("IdОценки")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_оценки");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdОценки"));

                    b.Property<int>("IdЗадания")
                        .HasColumnType("int")
                        .HasColumnName("ID_задания");

                    b.Property<int>("Балл")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ДатаОценки")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Дата_оценки")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("ДатаСдачи")
                        .HasColumnType("date")
                        .HasColumnName("Дата_сдачи");

                    b.Property<string>("Комментарий")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Преподаватель")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdОценки")
                        .HasName("PK__Оценки__7491505F506D2039");

                    b.HasIndex(new[] { "IdЗадания" }, "UQ__Оценки__D3DD242B0C03EA45")
                        .IsUnique();

                    b.ToTable("Оценки", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Преподаватели", b =>
                {
                    b.Property<int>("IdПреподавателя")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_преподавателя");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdПреподавателя"));

                    b.Property<string>("Должность")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Отчество")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Ставка")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4, 2)")
                        .HasDefaultValueSql("((1.0))");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdПреподавателя")
                        .HasName("PK__Преподав__5C1E636A9010CB9A");

                    b.ToTable("Преподаватели", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ПричиныОсвобождения", b =>
                {
                    b.Property<int>("IdПричины")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_причины");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdПричины"));

                    b.Property<string>("КодПричины")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Код_причины");

                    b.Property<int>("МаксДней")
                        .HasColumnType("int")
                        .HasColumnName("Макс_дней");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("ТребуетСправку")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Требует_справку");

                    b.HasKey("IdПричины")
                        .HasName("PK__ПричиныО__518A6CA02682A811");

                    b.HasIndex(new[] { "КодПричины" }, "UQ__ПричиныО__0DE9769C97695664")
                        .IsUnique();

                    b.ToTable("Причины_Освобождения", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Специальности", b =>
                {
                    b.Property<int>("IdСпециальности")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_специальности");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdСпециальности"));

                    b.Property<int>("IdОтделения")
                        .HasColumnType("int")
                        .HasColumnName("ID_отделения");

                    b.Property<string>("КодСпециальности")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Код_специальности");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdСпециальности")
                        .HasName("PK__Специаль__AB8BFED36633350D");

                    b.HasIndex("IdОтделения");

                    b.HasIndex(new[] { "КодСпециальности" }, "UQ__Специаль__042110197325F23D")
                        .IsUnique();

                    b.ToTable("Специальности", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Студенты", b =>
                {
                    b.Property<int>("IdСтудента")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_студента");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdСтудента"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdГруппы")
                        .HasColumnType("int")
                        .HasColumnName("ID_группы");

                    b.Property<DateTime?>("ДатаРегистрации")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Дата_регистрации")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("НомерЗачетки")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Номер_зачетки");

                    b.Property<string>("Отчество")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Телефон")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdСтудента")
                        .HasName("PK__Студенты__520B7B76874D27D1");

                    b.HasIndex("IdГруппы");

                    b.HasIndex(new[] { "НомерЗачетки" }, "UQ__Студенты__93450139A08F91DC")
                        .IsUnique();

                    b.ToTable("Студенты", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ТипыЗаданий", b =>
                {
                    b.Property<int>("IdТипаЗадания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_типа_задания");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdТипаЗадания"));

                    b.Property<string>("КодЗадания")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Код_задания");

                    b.Property<int>("МаксБалл")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5)
                        .HasColumnName("Макс_балл");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Описание")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdТипаЗадания")
                        .HasName("PK__ТипыЗада__AA5324F39E0A8232");

                    b.HasIndex(new[] { "КодЗадания" }, "UQ__ТипыЗада__C9CDA979A6907137")
                        .IsUnique();

                    b.ToTable("Типы_Заданий", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Группы", b =>
                {
                    b.HasOne("Domain.Models.Специальности", "IdСпециальностиNavigation")
                        .WithMany("Группыs")
                        .HasForeignKey("IdСпециальности")
                        .IsRequired()
                        .HasConstraintName("FK__Группы__ID_специ__412EB0B6");

                    b.Navigation("IdСпециальностиNavigation");
                });

            modelBuilder.Entity("Domain.Models.Задания", b =>
                {
                    b.HasOne("Domain.Models.Освобождения", "IdОсвобожденияNavigation")
                        .WithMany("Заданияs")
                        .HasForeignKey("IdОсвобождения")
                        .IsRequired()
                        .HasConstraintName("FK__Задания__ID_осво__571DF1D5");

                    b.HasOne("Domain.Models.ТипыЗаданий", "IdТипаЗаданияNavigation")
                        .WithMany("Заданияs")
                        .HasForeignKey("IdТипаЗадания")
                        .IsRequired()
                        .HasConstraintName("FK__Задания__ID_типа__5812160E");

                    b.Navigation("IdОсвобожденияNavigation");

                    b.Navigation("IdТипаЗаданияNavigation");
                });

            modelBuilder.Entity("Domain.Models.Нагрузка", b =>
                {
                    b.HasOne("Domain.Models.Группы", "IdГруппыNavigation")
                        .WithMany("Нагрузкаs")
                        .HasForeignKey("IdГруппы")
                        .IsRequired()
                        .HasConstraintName("FK__Нагрузка__ID_гру__6754599E");

                    b.HasOne("Domain.Models.Преподаватели", "IdПреподавателяNavigation")
                        .WithMany("Нагрузкаs")
                        .HasForeignKey("IdПреподавателя")
                        .IsRequired()
                        .HasConstraintName("FK__Нагрузка__ID_пре__66603565");

                    b.Navigation("IdГруппыNavigation");

                    b.Navigation("IdПреподавателяNavigation");
                });

            modelBuilder.Entity("Domain.Models.Освобождения", b =>
                {
                    b.HasOne("Domain.Models.ПричиныОсвобождения", "IdПричиныNavigation")
                        .WithMany("Освобожденияs")
                        .HasForeignKey("IdПричины")
                        .IsRequired()
                        .HasConstraintName("FK__Освобожде__ID_пр__4E88ABD4");

                    b.HasOne("Domain.Models.Студенты", "IdСтудентаNavigation")
                        .WithMany("Освобожденияs")
                        .HasForeignKey("IdСтудента")
                        .IsRequired()
                        .HasConstraintName("FK__Освобожде__ID_ст__4D94879B");

                    b.Navigation("IdПричиныNavigation");

                    b.Navigation("IdСтудентаNavigation");
                });

            modelBuilder.Entity("Domain.Models.Оценки", b =>
                {
                    b.HasOne("Domain.Models.Задания", "IdЗаданияNavigation")
                        .WithOne("Оценки")
                        .HasForeignKey("Domain.Models.Оценки", "IdЗадания")
                        .IsRequired()
                        .HasConstraintName("FK__Оценки__ID_задан__5EBF139D");

                    b.Navigation("IdЗаданияNavigation");
                });

            modelBuilder.Entity("Domain.Models.Специальности", b =>
                {
                    b.HasOne("Domain.Models.Отделения", "IdОтделенияNavigation")
                        .WithMany("Специальностиs")
                        .HasForeignKey("IdОтделения")
                        .IsRequired()
                        .HasConstraintName("FK__Специальн__ID_от__3C69FB99");

                    b.Navigation("IdОтделенияNavigation");
                });

            modelBuilder.Entity("Domain.Models.Студенты", b =>
                {
                    b.HasOne("Domain.Models.Группы", "IdГруппыNavigation")
                        .WithMany("Студентыs")
                        .HasForeignKey("IdГруппы")
                        .IsRequired()
                        .HasConstraintName("FK__Студенты__ID_гру__45F365D3");

                    b.Navigation("IdГруппыNavigation");
                });

            modelBuilder.Entity("Domain.Models.Группы", b =>
                {
                    b.Navigation("Нагрузкаs");

                    b.Navigation("Студентыs");
                });

            modelBuilder.Entity("Domain.Models.Задания", b =>
                {
                    b.Navigation("Оценки");
                });

            modelBuilder.Entity("Domain.Models.Освобождения", b =>
                {
                    b.Navigation("Заданияs");
                });

            modelBuilder.Entity("Domain.Models.Отделения", b =>
                {
                    b.Navigation("Специальностиs");
                });

            modelBuilder.Entity("Domain.Models.Преподаватели", b =>
                {
                    b.Navigation("Нагрузкаs");
                });

            modelBuilder.Entity("Domain.Models.ПричиныОсвобождения", b =>
                {
                    b.Navigation("Освобожденияs");
                });

            modelBuilder.Entity("Domain.Models.Специальности", b =>
                {
                    b.Navigation("Группыs");
                });

            modelBuilder.Entity("Domain.Models.Студенты", b =>
                {
                    b.Navigation("Освобожденияs");
                });

            modelBuilder.Entity("Domain.Models.ТипыЗаданий", b =>
                {
                    b.Navigation("Заданияs");
                });
#pragma warning restore 612, 618
        }
    }
}
